#!/usr/bin/env python3
# modified from mizuRoute/cime_config/buildnml

"""Namelist creator for wrfhydro model
"""

# Typically ignore this.
# pylint: disable=invalid-name

# Disable these because this is our standard setup
# pylint: disable=wildcard-import,unused-wildcard-import,wrong-import-position
# pylint: disable=multiple-imports
import os
import shutil
import sys

CIMEROOT = os.environ.get("CIMEROOT")
if CIMEROOT is None:
    raise SystemExit("ERROR: must set CIMEROOT environment variable")
_LIBDIR = os.path.join(CIMEROOT, "CIME", "Tools")
sys.path.append(_LIBDIR)
# Path for wrfhydro/route/settings for both a wrfhydro standalone checkout as
# well as a CESM checkout
sys.path.append(os.path.join(CIMEROOT, "./"))
search_path = ("../components/wrfhydro/"
               "src/CPL/CTSM_cpl/route/settings")
sys.path.append(os.path.join(CIMEROOT, search_path))

from standard_script_setup import *
from CIME.case import Case
from CIME.nmlgen import NamelistGenerator
from CIME.XML.files import Files
from CIME.utils import expect, safe_copy
from CIME.buildnml import create_namelist_infile, parse_input
from wrfhydro_namelist import wrfhydro_namelist

logger = logging.getLogger(__name__)

def buildnml(case, caseroot, compname):
    """Build the wrfhydro control file """

    # cp the namelist file
    if compname != "wrfhydro":
        raise AttributeError

    srcroot = case.get_value("COMP_ROOT_DIR_ROF")
    rundir = case.get_value("RUNDIR")

    nmltemplate = "hydro.namelist.template"
    nmlsrc = os.path.join(srcroot+'/cime_config', nmltemplate)

    nmlfile = "hydro.namelist"
    nmldestination = os.path.join(rundir, nmlfile)

    print(f"   - copying namelist {nmltemplate} to {nmldestination}")
    shutil.copy(nmlsrc, nmldestination)

def _main_func():
    caseroot = parse_input(sys.argv)
    with Case(case_root=caseroot) as case:
        buildnml(case, caseroot, "wrfhydro")

if __name__ == "__main__":
    _main_func()
