#!/usr/bin/env python3
# modified from mizuRoute/cime_config/buildlib

import sys, os
_CIMEROOT = os.environ.get("CIMEROOT")
if _CIMEROOT is None:
    raise SystemExit("ERROR: must set CIMEROOT environment variable")
_LIBDIR = os.path.join(_CIMEROOT, "scripts", "Tools")
sys.path.append(_LIBDIR)

from CIME.buildlib import parse_input
from CIME.build import get_standard_cmake_args
from CIME.case import Case
from CIME.utils import run_cmd, expect
from standard_script_setup import *

logger = logging.getLogger(__name__)


def get_values(case):
    casetools = case.get_value("CASETOOLS")
    # in config_files.xml :   <entry id="COMP_ROOT_DIR_ROF">
    # ./cime/CIME/data/config/cesm/config_files.xml
    # ./components/cism/cime/CIME/data/config/ufs/config_files.xml
    rof_root = case.get_value("COMP_ROOT_DIR_ROF")
    gmake_j = case.get_value("GMAKE_J")
    gmake = case.get_value("GMAKE")
    # from where? could be nuopc and others
    driver = case.get_value("COMP_INTERFACE").lower()
    return casetools, rof_root, gmake_j, gmake, driver

def create_filepath(bldroot, rof_root):
    filepath_file = os.path.join(bldroot,"Filepath")
    if not os.path.isfile(filepath_file):
        caseroot = case.get_value("CASEROOT")
        paths = [#os.path.join(caseroot,"SourceMods","src.wrfhydro"),
                 os.path.join(rof_root),
                 os.path.join(rof_root,"src"),
                 os.path.join(rof_root,"src","CPL","CTSM_cpl")] #,driver)]
        with open(filepath_file, "w") as filepath:
            filepath.write("\n".join(paths))
            filepath.write("\n")

def create_library(libroot, casetools, gmake, gmake_j):
    complib = os.path.join(libroot,"librof.a")
    cmakefile = os.path.join(casetools, "CMake")

    cmd = "{} complib -j {} COMP_NAME=wrfhydro COMPLIB={} -f {} {}" \
        .format(gmake, gmake_j, complib, cmakefile,
                get_standard_cmake_args(case))

    rc, out, err = run_cmd(cmd)
    logger.info("%s: \n\n output:\n %s \n\n err:\n\n%s\n"%(cmd,out,err))
    expect(rc == 0, "Command %s failed with rc=%s" % (cmd, rc))

def _main_func():
    caseroot, libroot, bldroot = parse_input(sys.argv)
    with Case(caseroot) as case:
         casetools, rof_root, gmake_j, gmake, driver = get_values(case)
         expect( driver == "nuopc", "wrfhydro only has a nuopc COMP_INTERFACE" )

         create_filepath(bldroot, rof_root)
         create_library(libroot, casetools, gmake, gmake_j)

###############################################################################

if __name__ == "__main__":
    _main_func()
