.. |image7| image:: media/image14.png
   :width: 7in
   :height: 3.13889in
.. |image18| image:: media/image11.png
   :width: 0.19792in
   :height: 0.19792in
.. |image19| image:: media/image34.png
   :width: 1.00972in
   :height: 0.40556in
.. |image20| image:: media/image32.png
   :width: 2.38681in
   :height: 0.41528in
.. |image21| image:: media/image40.png
   :width: 0.14167in
   :height: 0.15069in
.. |image22| image:: media/image37.png
   :width: 0.77361in
   :height: 0.5in
.. |image23| image:: media/image36.png
   :width: 1in
   :height: 0.40556in
.. |image28| image:: media/image45.png
   :width: 0.32813in
   :height: 0.32813in
.. |image36| image:: media/image64.png
   :width: 2.25872in
   :height: 1.66875in
.. |image37| image:: media/image66.png
   :width: 2.2587in
   :height: 1.9223in
.. |image38| image:: media/image62.png
   :width: 1.77083in
   :height: 1.58333in
.. |image40| image:: media/image35.png
   :width: 7in
   :height: 3.70833in
.. |image42| image:: media/image17.png
   :width: 7in
   :height: 5.22222in
.. |image43| image:: media/image39.png
   :width: 7.42188in
   :height: 5.5852in
.. |image44| image:: media/image25.png
   :width: 4.09546in
   :height: 3.05729in
